import React, { useState, useRef, useEffect } from 'react';
import {
  Layout,
  Typography,
  Input,
  Button,
  Avatar,
  Card,
  Spin,
  Space,
  Breadcrumb,
} from 'antd';
import {
  SendOutlined,
  RobotOutlined,
  UserOutlined,
  HomeOutlined,
} from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import { logout } from '../../store/slices/authSlice';

const { Header, Content, Sider } = Layout;
const { Title, Text, Paragraph } = Typography;
const { TextArea } = Input;

const INITIAL_MESSAGES = [
  {
    id: 1,
    role: 'assistant',
    content: 'Hello! I\'m your AI learning assistant. Ask me anything about your courses, and I\'ll do my best to help you understand the concepts.',
  },
];

function QAAssistantPage() {
  const [messages, setMessages] = useState(INITIAL_MESSAGES);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const messagesEndRef = useRef(null);
  const navigate = useNavigate();
  const dispatch = useDispatch();

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async () => {
    const trimmed = input.trim();
    if (!trimmed) return;

    const userMsg = { id: Date.now(), role: 'user', content: trimmed };
    setMessages((prev) => [...prev, userMsg]);
    setInput('');
    setLoading(true);

    try {
      // Placeholder — replace with real API call to /api/qa/ask
      await new Promise((resolve) => setTimeout(resolve, 1200));
      const assistantMsg = {
        id: Date.now() + 1,
        role: 'assistant',
        content: `Great question! You asked: "${trimmed}". In a production environment, this response would be generated by the AI backend. The system is designed to provide contextual answers based on your course materials.`,
      };
      setMessages((prev) => [...prev, assistantMsg]);
    } catch {
      setMessages((prev) => [
        ...prev,
        { id: Date.now() + 1, role: 'assistant', content: 'Sorry, I encountered an error. Please try again.' },
      ]);
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleLogout = () => {
    dispatch(logout());
    navigate('/login');
  };

  return (
    <Layout className="min-h-screen">
      <Header className="flex items-center justify-between bg-blue-600 px-6">
        <div className="flex items-center gap-3">
          <RobotOutlined className="text-white text-xl" />
          <Title level={4} className="!text-white !mb-0">
            Course Buddy
          </Title>
        </div>
        <Button type="text" className="!text-white" onClick={handleLogout}>
          Logout
        </Button>
      </Header>

      <Layout>
        <Sider width={220} className="bg-white shadow-sm">
          <nav className="py-4">
            {[
              { path: '/courses', label: 'Course Library', icon: '📚' },
              { path: '/qa', label: 'Q&A Assistant', icon: '🤖' },
              { path: '/collaboration', label: 'Collaboration', icon: '👥' },
              { path: '/notes', label: 'My Notes', icon: '📝' },
            ].map((item) => (
              <div
                key={item.path}
                className={`px-4 py-3 cursor-pointer hover:bg-blue-50 transition-colors ${
                  window.location.pathname === item.path ? 'bg-blue-50 text-blue-600 font-medium border-r-2 border-blue-600' : 'text-gray-700'
                }`}
                onClick={() => navigate(item.path)}
              >
                <span className="mr-2">{item.icon}</span>
                {item.label}
              </div>
            ))}
          </nav>
        </Sider>

        <Content className="p-6 bg-gray-50 flex flex-col">
          <Breadcrumb
            className="mb-4"
            items={[
              { href: '/', title: <HomeOutlined /> },
              { title: 'Q&A Assistant' },
            ]}
          />

          <Card className="flex-1 flex flex-col" styles={{ body: { display: 'flex', flexDirection: 'column', height: '100%', padding: '16px' } }}>
            <Title level={4} className="mb-4">
              🤖 AI Q&amp;A Assistant
            </Title>

            {/* Messages */}
            <div className="flex-1 overflow-y-auto mb-4 space-y-4" style={{ maxHeight: 'calc(100vh - 340px)' }}>
              {messages.map((msg) => (
                <div
                  key={msg.id}
                  className={`flex gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}
                >
                  <Avatar
                    icon={msg.role === 'user' ? <UserOutlined /> : <RobotOutlined />}
                    className={msg.role === 'user' ? 'bg-blue-500' : 'bg-green-500'}
                  />
                  <div
                    className={`max-w-xl px-4 py-3 rounded-2xl text-sm ${
                      msg.role === 'user'
                        ? 'bg-blue-500 text-white rounded-tr-sm'
                        : 'bg-white border border-gray-200 text-gray-800 rounded-tl-sm'
                    }`}
                  >
                    {msg.content}
                  </div>
                </div>
              ))}
              {loading && (
                <div className="flex gap-3">
                  <Avatar icon={<RobotOutlined />} className="bg-green-500" />
                  <div className="bg-white border border-gray-200 rounded-2xl rounded-tl-sm px-4 py-3">
                    <Spin size="small" />
                    <Text className="ml-2 text-gray-500 text-sm">Thinking…</Text>
                  </div>
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>

            {/* Input area */}
            <Space.Compact className="w-full">
              <TextArea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Ask a question… (Enter to send, Shift+Enter for new line)"
                autoSize={{ minRows: 1, maxRows: 4 }}
                disabled={loading}
                className="flex-1"
              />
              <Button
                type="primary"
                icon={<SendOutlined />}
                onClick={handleSend}
                loading={loading}
                disabled={!input.trim()}
              >
                Send
              </Button>
            </Space.Compact>
          </Card>
        </Content>
      </Layout>
    </Layout>
  );
}

export default QAAssistantPage;
